on:
  workflow_dispatch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]
        poetry-version: [ "1.8.5" ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Poetry update
        run: poetry update
      - name: Poetry install
        run: poetry install
      - name: Run script
        run: poetry run mihomo_speedtest
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
          SUBSCRIPTIONS: ${{ vars.SUBSCRIPTIONS }}
          FILE: ${{ vars.FILE }}
          TEMPLATE: ${{ vars.TEMPLATE }}
      - name: Create a release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Generated config
          prerelease: true
          files: |
            result/config_best_50.yml
            result/config_best_100.yml
          tag_name: pre-release
